# Jarvis Testing

The pipeline object can export .npy files.  I'll have to expose this as part of the debugging interface.

In this note, I'm loading values from Jarvis C++ and comparing against numpy computed values.

In [1]:
import numpy as np

In [18]:
processed_audio = np.load("processed_audio_0.npy")

In [20]:
processed_audio.shape

(256, 2112)

In [21]:
processed_audio[0]

array([0.00019226, 0.00019226, 0.00019226, ..., 0.00019226, 0.00019226,
       0.        ], dtype=float32)

In [24]:
t = processed_audio[0][96:96+320]

In [26]:
t.shape

(320,)

In [29]:
t

array([0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019226,
       0.00019226, 0.00019226, 0.00019226, 0.00019226, 0.00019

In [27]:
tw = t * np.hanning(320)

1.86466664e-08, 7.45794253e-08, 1.67776577e-07,

In [28]:
tw

array([0.00000000e+00, 1.86466655e-08, 7.45794280e-08, 1.67776589e-07,
       2.98201994e-07, 4.65805045e-07, 6.70520723e-07, 9.12269610e-07,
       1.19095792e-06, 1.50647755e-06, 1.85870608e-06, 2.24750687e-06,
       2.67272910e-06, 3.13420781e-06, 3.63176396e-06, 4.16520453e-06,
       4.73432259e-06, 5.33889735e-06, 5.97869426e-06, 6.65346514e-06,
       7.36294820e-06, 8.10686821e-06, 8.88493657e-06, 9.69685145e-06,
       1.05422979e-05, 1.14209478e-05, 1.23324605e-05, 1.32764822e-05,
       1.42526468e-05, 1.52605756e-05, 1.62998775e-05, 1.73701493e-05,
       1.84709759e-05, 1.96019303e-05, 2.07625735e-05, 2.19524555e-05,
       2.31711146e-05, 2.44180780e-05, 2.56928620e-05, 2.69949721e-05,
       2.83239031e-05, 2.96791394e-05, 3.10601553e-05, 3.24664151e-05,
       3.38973732e-05, 3.53524745e-05, 3.68311545e-05, 3.83328396e-05,
       3.98569471e-05, 4.14028859e-05, 4.29700562e-05, 4.45578501e-05,
       4.61656515e-05, 4.77928367e-05, 4.94387745e-05, 5.11028264e-05,
      

compare computing hanning window vs jarvis window

In [4]:
fft_windows = np.load("fft_windows_0.npy")

In [6]:
fft_windows.shape

(2816, 512)

In [31]:
np.allclose(tw, fft_windows[0][96:96+320])

True

# FFT

In [76]:
mag_frames = np.fft.rfft(fft_windows[0])  # Magnitude of the FFT

In [77]:
mag_frames.shape

(257,)

values i computed (real imaginary)


        3.06660272e-02,  0.00000000e+00, -2.37175561e-02, -1.45530881e-04,
        9.89658199e-03,  1.21455319e-04, -8.36762134e-04, -1.54045192e-05,
       -7.51180458e-04, -1.84404435e-05, -1.27427600e-04, -3.91059621e-06,

In [78]:
mag_frames

array([ 3.06660279e-02+0.00000000e+00j, -2.37175555e-02-1.45530924e-04j,
        9.89658212e-03+1.21455432e-04j, -8.36762110e-04-1.54046640e-05j,
       -7.51180517e-04-1.84404467e-05j, -1.27427584e-04-3.91065634e-06j,
        1.47347123e-04+5.42711592e-06j,  1.12491132e-04+4.83463196e-06j,
       -4.02526021e-06-1.97748354e-07j, -5.38735671e-05-2.97810458e-06j,
       -2.73900963e-05-1.68274762e-06j,  1.37286170e-05+9.28024788e-07j,
        2.36528619e-05+1.74473991e-06j,  5.72452428e-06+4.57599079e-07j,
       -1.13620401e-05-9.78440392e-07j, -1.06579674e-05-9.83726368e-07j,
        9.70972135e-07+9.56324082e-08j,  7.90311888e-06+8.27382832e-07j,
        4.33232571e-06+4.80445874e-07j, -2.86979381e-06-3.36091896e-07j,
       -5.00149019e-06-6.16874978e-07j, -1.13370810e-06-1.46897162e-07j,
        3.00497591e-06+4.08124646e-07j,  2.84095576e-06+4.03616506e-07j,
       -4.25618352e-07-6.31345185e-08j, -2.49011391e-06-3.85003272e-07j,
       -1.33307847e-06-2.14494142e-07j,  1.07514925

In [71]:
jps = np.load("fft_bins_0.npy")

In [72]:
jps.shape

(2816, 514)

In [91]:
jps[0].shape

(514,)

In [92]:
jps[0]

array([ 3.06660272e-02,  0.00000000e+00, -2.37175561e-02, -1.45530881e-04,
        9.89658199e-03,  1.21455319e-04, -8.36762134e-04, -1.54045192e-05,
       -7.51180458e-04, -1.84404435e-05, -1.27427600e-04, -3.91059621e-06,
        1.47347047e-04,  5.42707039e-06,  1.12491194e-04,  4.83474923e-06,
       -4.02520800e-06, -1.97745564e-07, -5.38736276e-05, -2.97806355e-06,
       -2.73901605e-05, -1.68279394e-06,  1.37286215e-05,  9.28182885e-07,
        2.36530923e-05,  1.74480692e-06,  5.72456338e-06,  4.57765651e-07,
       -1.13621591e-05, -9.79137667e-07, -1.06580710e-05, -9.81888661e-07,
        9.70929591e-07,  9.56282236e-08,  7.90298873e-06,  8.27453164e-07,
        4.33227615e-06,  4.80313247e-07, -2.86981822e-06, -3.36073015e-07,
       -5.00139868e-06, -6.16851537e-07, -1.13366968e-06, -1.46923753e-07,
        3.00490456e-06,  4.08123668e-07,  2.84082762e-06,  4.03732940e-07,
       -4.25573120e-07, -6.31276578e-08, -2.49006825e-06, -3.84936584e-07,
       -1.33309936e-06, -

In [89]:
pow_frames = np.abs(mag_frames)

In [90]:
pow_frames

array([3.06660279e-02, 2.37180020e-02, 9.89732737e-03, 8.36903896e-04,
       7.51406827e-04, 1.27487577e-04, 1.47447036e-04, 1.12594975e-04,
       4.03011466e-06, 5.39558184e-05, 2.74417386e-05, 1.37599474e-05,
       2.37171244e-05, 5.74278462e-06, 1.14040914e-05, 1.07032699e-05,
       9.75670254e-07, 7.94631049e-06, 4.35888452e-06, 2.88940725e-06,
       5.03938874e-06, 1.14318538e-06, 3.03256426e-06, 2.86948356e-06,
       4.30275433e-07, 2.51970134e-06, 1.35022441e-06, 1.09007444e-06,
       1.81744439e-06, 3.53647179e-07, 1.23609098e-06, 1.13379455e-06,
       2.40659696e-07, 1.10545396e-06, 5.61049199e-07, 5.38275278e-07,
       8.45629834e-07, 1.31583047e-07, 6.27163954e-07, 5.49777910e-07,
       1.53445050e-07, 5.80477396e-07, 2.74657809e-07, 3.10211534e-07,
       4.57036550e-07, 5.16015716e-08, 3.63581204e-07, 3.02179637e-07,
       1.05990288e-07, 3.41754090e-07, 1.48809213e-07, 1.97444834e-07,
       2.72559492e-07, 1.83008436e-08, 2.30326527e-07, 1.80768358e-07,
      

In [95]:
computed_power_spectrum = pow_frames **2

In [83]:
power_spectrum = np.load("power_spectrum_0.npy")

In [84]:
power_spectrum[0]

array([9.40405240e-04, 5.62543632e-04, 9.79570832e-05, 7.00408179e-07,
       5.64612151e-07, 1.62530860e-08, 2.17406058e-08, 1.26776438e-08,
       1.62414023e-11, 2.91123659e-09, 7.53052676e-10, 1.89336574e-10,
       5.62513147e-10, 3.29801741e-11, 1.30057368e-10, 1.14558585e-10,
       9.51849060e-13, 6.31419084e-11, 1.89993177e-11, 8.34880168e-12,
       2.53944938e-11, 1.30679354e-12, 9.19601634e-12, 8.23330206e-12,
       1.85097583e-13, 6.34861608e-12, 1.82316402e-12, 1.18823994e-12,
       3.30288769e-12, 1.25080420e-13, 1.52692258e-12, 1.28783464e-12,
       5.79102670e-14, 1.22175414e-12, 3.14895869e-13, 2.89752705e-13,
       7.14934947e-13, 1.73013052e-14, 3.93306210e-13, 3.02164489e-13,
       2.35802114e-14, 3.37048315e-13, 7.54394309e-14, 9.62024514e-14,
       2.08857400e-13, 2.65663329e-15, 1.31513059e-13, 9.29377154e-14,
       1.11913796e-14, 1.16691311e-13, 2.21664948e-14, 3.89988097e-14,
       7.43259553e-14, 3.35524679e-16, 5.30692095e-14, 3.26848500e-14,
      

In [96]:
np.allclose(power_spectrum[0], computed_power_spectrum)

True

# Mel Banks

In [97]:
import librosa

In [98]:
sample_freq = 16000
num_fft = 512
num_features = 64
mel_basis = librosa.filters.mel(sample_freq, num_fft, n_mels=num_features, fmin=0, fmax=int(sample_freq / 2))

In [100]:
mel_basis.shape

(64, 257)

In [102]:
mels = np.log(np.dot(mel_basis, power_spectrum[0]) + 5.96046448e-8)

In [103]:
mels

array([-11.553577, -14.025979, -16.4954  , -16.624582, -16.631945,
       -16.63447 , -16.63523 , -16.635315, -16.63548 , -16.635475,
       -16.635515, -16.635515, -16.635525, -16.635527, -16.635529,
       -16.63553 , -16.63553 , -16.635532, -16.63553 , -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532], dtype=float32)

In [104]:
computed_mels = np.load("mel_features_0.npy")

In [105]:
computed_mels[0]

array([-11.553577, -14.025979, -16.4954  , -16.624582, -16.631945,
       -16.63447 , -16.63523 , -16.635315, -16.63548 , -16.635475,
       -16.635515, -16.635515, -16.635525, -16.635527, -16.635529,
       -16.63553 , -16.63553 , -16.635532, -16.63553 , -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532], dtype=float32)

In [107]:
np.allclose(mels, computed_mels[0])

True

In [109]:
computed_mels[3]

array([-11.553577, -14.025979, -16.4954  , -16.624582, -16.631945,
       -16.63447 , -16.63523 , -16.635315, -16.63548 , -16.635475,
       -16.635515, -16.635515, -16.635525, -16.635527, -16.635529,
       -16.63553 , -16.63553 , -16.635532, -16.63553 , -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532, -16.635532,
       -16.635532, -16.635532, -16.635532, -16.635532], dtype=float32)